⚗️ trying the LLVM install script
Signed-off-by: burgholzer <burgholzer@me.com>

diff --git a/.readthedocs.yaml b/.readthedocs.yaml
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -12,12 +12,12 @@ build:
   tools:
     python: "3.12"
   apt_packages:
-    - clang
-    - cmake
+    #    - clang
+    #    - cmake
     - graphviz
     - inkscape
-    - lld
-    - ninja-build
+  #    - lld
+  #    - ninja-build
   jobs:
     post_checkout:
       # Skip docs build if the commit message contains "skip ci"
@@ -35,33 +35,51 @@ build:
       - asdf plugin add uv
       - asdf install uv latest
       - asdf global uv latest
-      # Set up MLIR
-      - git clone https://github.com/llvm/llvm-project.git
-      - mkdir llvm-project/build
+      - uv tool install cmake
+      - uv tool install ninja
+      - wget https://apt.llvm.org/llvm.sh -O llvm_install.sh
+      - chmod +x llvm_install.sh
       - >
-        cmake -G Ninja -S llvm-project/llvm -B llvm-project/build
-        -DLLVM_ENABLE_PROJECTS=mlir
-        -DLLVM_BUILD_EXAMPLES=OFF
-        -DLLVM_BUILD_TESTS=OFF
-        -DCMAKE_BUILD_TYPE=Release
-        -DLLVM_ENABLE_ASSERTIONS=ON
-        -DCMAKE_C_COMPILER=clang
-        -DCMAKE_CXX_COMPILER=clang++
-        -DLLVM_ENABLE_LLD=ON
-      - cmake --build llvm-project/build --config Release
-      - export MLIR_DIR=$READTHEDOCS_OUTPUT/llvm-project/build/lib/cmake/mlir
-      - export LLVM_DIR=$READTHEDOCS_OUTPUT/llvm-project/build/lib/cmake/llvm
-      - cmake --install llvm-project/build --prefix $READTHEDOCS_OUTPUT/llvm-install
+        if llvm_install.sh 20; then
+          apt install libmlir-20-dev \
+          mlir-20-tools \
+          clang-20 \
+          clang-tools-20 \
+          || exit 1
+        else
+          echo "Installation from script failed."
+          exit 1
+        fi
+      - export CC=clang-20
+      - export CXX=clang++-20
+      - export MLIR_DIR=/usr/lib/llvm-20/lib/cmake/mlir
+      - export LLVM_DIR=/usr/lib/llvm-20/lib/cmake/llvm
+      # Set up MLIR
+      #      - git clone https://github.com/llvm/llvm-project.git
+      #      - mkdir llvm-project/build
+      #      - >
+      #        cmake -G Ninja -S llvm-project/llvm -B llvm-project/build
+      #        -DLLVM_ENABLE_PROJECTS=mlir
+      #        -DLLVM_BUILD_EXAMPLES=OFF
+      #        -DLLVM_BUILD_TESTS=OFF
+      #        -DCMAKE_BUILD_TYPE=Release
+      #        -DLLVM_ENABLE_ASSERTIONS=ON
+      #        -DCMAKE_C_COMPILER=clang
+      #        -DCMAKE_CXX_COMPILER=clang++
+      #        -DLLVM_ENABLE_LLD=ON
+      #      - cmake --build llvm-project/build --config Release
+      #      - export MLIR_DIR=$READTHEDOCS_OUTPUT/llvm-project/build/lib/cmake/mlir
+      #      - export LLVM_DIR=$READTHEDOCS_OUTPUT/llvm-project/build/lib/cmake/llvm
+      #      - cmake --install llvm-project/build --prefix $READTHEDOCS_OUTPUT/llvm-install
       # Build the MLIR documentation
       - >
         cmake -G Ninja -S . -B build
         -DCMAKE_BUILD_TYPE=Release
         -DBUILD_MQT_CORE_MLIR=ON
-        -DCMAKE_C_COMPILER=clang
-        -DCMAKE_CXX_COMPILER=clang++
-        -DLLVM_DIR=$LLVM_DIR
-        -DMLIR_DIR=$MLIR_DIR
-        -DBUILD_MQT_CORE_MLIR=ON
+      #        -DCMAKE_C_COMPILER=clang
+      #        -DCMAKE_CXX_COMPILER=clang++
+      #        -DLLVM_DIR=$LLVM_DIR
+      #        -DMLIR_DIR=$MLIR_DIR
       - cmake --build build --target mlir-doc
     build:
       html:
